name: Slacktification
description: Send slack notification on success or failure
author: Yorick <yorick@ctrlalt.dev>
branding:
  icon: alert-octagon
  color: red
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  slack_webhook_url:
    required: true
    description: The slack webhook url to send the payload to
  payload:
    required: true
    description: The payload to send, JSON formatted - see https://api.slack.com/block-kit/building
