name: Slack Notification
description: Send slack notification on success or failure
author: Yorick <yorick@ctrlalt.dev>
inputs:
  slack_webhook_url:
    required: true
    description: The slack webhook url to send the payload to
runs:
  using: 'node16'
  main: 'dist/main.js'
