name: Slack Notification
description: Send slack notification on success or failure
author: Yorick <yorick@ctrlalt.dev>
branding:
  icon: alert-octagon
  color: red
runs:
  using: 'node16'
  main: 'dist/index.js'
inputs:
  slack_webhook_url:
    required: true
    description: The slack webhook url to send the payload to
  success:
    required: true
    description: Whether the action was successful or not
    default: 'true'
